routing:
  providers: 
    - ors_api
  default_provider: ors_api
  provider_options:
    ors_api:
      url: http://localhost:8082
demand:
  population_file: ./files/population_hannover.csv
  run_interval: 1
  delete_interval: 5
