routing:
  providers:
    - ors-api
    - distance
  default_provider: distance
  provider_options:
    ors-api:
      url: http://172.26.62.41:8080/ors
    distance:
      metric: eucledian
      speed: 50
demand:
  run_interval: 1
  delete_interval: 5
