routing:
  providers:
    - ors-api
    - distance
  default_provider: ors-api
  provider_options:
    ors-api:
      url: http://proxy/ors/ors
    distance:
      metric: eucledian
      speed: 50
demand:
  run_interval: 1
  delete_interval: 5
